import os

lines = [
    "# ============================================================",
    "# APPLY ALL FIXES -- run this from your project root:",
    "#   cd C:\\Users\\mourish\\Desktop\\SIH2k25\\SIH-MDR_PATHOGEN-Final\\script",
    "#   .\\APPLY_ALL_FIXES.ps1",
    "# ============================================================",
    "",
    "Write-Host \"\"",
    "Write-Host \"=== Patient Contact Tracing -- Applying All Fixes ===\" -ForegroundColor Cyan",
    "Write-Host \"\"",
    "",
    "# -- FIX 1: Delete stale sklearn mask model (version mismatch) --",
    "$maskModel = \"src\\mask_datas\\mask_detector.joblib\"",
    "if (Test-Path $maskModel) {",
    "    Remove-Item $maskModel -Force",
    "    Write-Host \"[FIX 1] Deleted stale mask_detector.joblib (sklearn version mismatch)\" -ForegroundColor Green",
    "    Write-Host \"        It will be retrained automatically on next startup.\" -ForegroundColor Gray",
    "} else {",
    "    Write-Host \"[FIX 1] mask_detector.joblib not found -- nothing to delete (OK)\" -ForegroundColor Yellow",
    "}",
    "",
    "# -- FIX 2: Check monitor_service.py _build_tracker --",
    "$monitorFile = \"src\\monitor_service.py\"",
    "if (Test-Path $monitorFile) {",
    "    $content = Get-Content $monitorFile -Raw",
    "    if ($content -match \"_build_tracker\") {",
    "        if ($content -match \"candidate_src\") {",
    "            Write-Host \"[FIX 2] _build_tracker already patched -- skipping\" -ForegroundColor Yellow",
    "        } else {",
    "            Write-Host \"[FIX 2] _build_tracker found but not yet patched -- applying...\" -ForegroundColor Cyan",
    "            # Apply patch via Python to avoid PowerShell here-string issues",
    "            python src\\apply_monitor_patch.py",
    "        }",
    "    } else {",
    "        Write-Host \"[FIX 2] ERROR: Could not find _build_tracker in monitor_service.py\" -ForegroundColor Red",
    "    }",
    "} else {",
    "    Write-Host \"[FIX 2] monitor_service.py not found -- skipping\" -ForegroundColor Yellow",
    "}",
    "",
    "# -- FIX 3: Check mask_classifier.py --",
    "$maskFile = \"src\\mask_classifier.py\"",
    "if (Test-Path $maskFile) {",
    "    $maskContent = Get-Content $maskFile -Raw",
    "    if ($maskContent -match \"version_err\") {",
    "        Write-Host \"[FIX 3] mask_classifier.py already patched -- skipping\" -ForegroundColor Yellow",
    "    } else {",
    "        Write-Host \"[FIX 3] Applying mask_classifier.py patch...\" -ForegroundColor Cyan",
    "        python src\\apply_mask_patch.py",
    "    }",
    "} else {",
    "    Write-Host \"[FIX 3] mask_classifier.py not found -- skipping\" -ForegroundColor Yellow",
    "}",
    "",
    "# -- FIX 4: Upgrade scikit-learn --",
    "Write-Host \"\"",
    "Write-Host \"[FIX 4] Upgrading scikit-learn...\" -ForegroundColor Cyan",
    "pip install scikit-learn --upgrade --quiet",
    "Write-Host \"[FIX 4] scikit-learn upgrade done\" -ForegroundColor Green",
    "",
    "# -- VERIFY --",
    "Write-Host \"\"",
    "Write-Host \"=== Verification ===\" -ForegroundColor Cyan",
    "python src\\verify_fixes.py",
    "",
    "Write-Host \"\"",
    "Write-Host \"=== Done! Now restart your backend: ===\" -ForegroundColor Cyan",
    "Write-Host \"   python backend/main.py\" -ForegroundColor White",
    "Write-Host \"   -- or --\" -ForegroundColor Gray",
    "Write-Host \"   uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000\" -ForegroundColor White",
    "Write-Host \"\"",
]

content = "\r\n".join(lines) + "\r\n"
with open("APPLY_ALL_FIXES.ps1", "wb") as f:
    f.write(content.encode("utf-8"))

size = os.path.getsize("APPLY_ALL_FIXES.ps1")
print(f"Written APPLY_ALL_FIXES.ps1 with CRLF ({size} bytes)")

# Also write verify_fixes.py
verify_lines = [
    "import sys, os",
    "sys.path.insert(0, 'src')",
    "sys.path.insert(0, 'backend')",
    "errors = []",
    "",
    "# Check 1: reid_tracker patch",
    "try:",
    "    import reid_tracker",
    "    if not hasattr(reid_tracker, '_patch_torch_load_for_ultralytics'):",
    "        errors.append('reid_tracker.py patch NOT found')",
    "    else:",
    "        print('[OK] reid_tracker.py patch is active')",
    "except Exception as e:",
    "    errors.append(f'reid_tracker import failed: {e}')",
    "",
    "# Check 2: YOLO loads",
    "try:",
    "    from ultralytics import YOLO",
    "    from pathlib import Path",
    "    pt = Path('src/yolov8n.pt')",
    "    if pt.exists():",
    "        try:",
    "            YOLO(str(pt))",
    "            print('[OK] YOLO model loads successfully')",
    "        except Exception as e:",
    "            errors.append(f'YOLO load failed: {e}')",
    "    else:",
    "        errors.append('src/yolov8n.pt not found')",
    "except Exception as e:",
    "    errors.append(f'ultralytics import failed: {e}')",
    "",
    "# Check 3: mask_detector.joblib deleted",
    "if not os.path.exists('src/mask_datas/mask_detector.joblib'):",
    "    print('[OK] Stale mask_detector.joblib removed')",
    "else:",
    "    print('[WARN] mask_detector.joblib still exists (will warn but not crash)')",
    "",
    "# Check 4: sklearn version",
    "import sklearn",
    "print(f'[OK] scikit-learn version: {sklearn.__version__}')",
    "",
    "if errors:",
    "    print()",
    "    for e in errors:",
    "        print(f'[ERROR] {e}')",
    "else:",
    "    print()",
    "    print('All checks passed! Restart your FastAPI backend now.')",
]

verify_content = "\n".join(verify_lines) + "\n"
os.makedirs("src", exist_ok=True)
with open("src/verify_fixes.py", "w", encoding="utf-8") as f:
    f.write(verify_content)
print("Written src/verify_fixes.py")
